#---------springboot配置信息---------
server: 
    host: localhost #服务域名
    port: 8088 #服务端口
    session: 
        timeout: 3000000 #session过期时间

#---------自定义日志配置文件的名称和位置
logging: 
    config: classpath:logback-spring.xml
    dir: d://log
    
#---------单点登陆客户（cas client）端配置-------------
cas: 
    signOutFilters: /logout   #需要拦截退出登陆的请求规则
    authFilters: /*  #需要拦截校验是否登陆过的请求规则
    validateFilters: /*   #需要拦截ticket的校验的请求规则
    requestWrapperFilters: /*  #存放用户信息到当前request域中的请求规则，存储后可在web层获取当前用户信息
    assertionFilters: /*  #存放用户信息到本地线程变量的请求规则，存储后可在业务层获取当前用户信息
    #casServerUrlPrefix: https://www.casserver.com:8443/seally-sso #单点登陆系统的根访问路径（=========需要根据实际部署的服务器对应修改==========）
    casServerUrlPrefix: http://www.seally.cn:8080/seally-sso #去除https认证后使用http访问
    casServerLoginUrl: ${cas.casServerUrlPrefix}/login #单点登陆系统的登录地址 https://www.casserver.com:8443/seally-sso/login
    casServerLogOutUrl: ${cas.casServerUrlPrefix}/logout #单点登陆系统的登出地址 https://www.casserver.com:8443/seally-sso/logout
    redirectAfterValidation: true 
    useSession: true 
    clientAppServerUrl: http://${server.host}:${server.port}/ #客户端应用登录成功后访问（首页访问路径,注意路径末尾的/要带上=========需要根据实际部署的客户端服务对应修改==========）
#如果服务名后面不配置“/”,启动服务访问报错：Ticket 'ST-2-cTeTf5W45sSBjPAaBfgG-cas01.example.org' does not match supplied service. The original service was 'http://localhost:8090' and the supplied service was 'http://localhost:8090/'

#---------mysql数据库配置信息---------
spring: 
    datasource:
        name: myDataSource
        url: jdbc:mysql://www.seally.cn:3306/dennis?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource #配置使用druid连接池
        initialSize: 5   #以下为druid连接池补充配置信息，应用到上面所有数据源中 
        minIdle: 5  
        maxActive: 20  
        maxWait: 60000    # 配置获取连接等待超时的时间  
        timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
        minEvictableIdleTimeMillis: 300000    # 配置一个连接在池中最小生存的时间，单位是毫秒  
        validationQuery: SELECT 1 FROM DUAL  
        testWhileIdle: true  
        testOnBorrow: false  
        testOnReturn: false  
        poolPreparedStatements: true   # 打开PSCache，并且指定每个连接上PSCache的大小  
        maxPoolPreparedStatementPerConnectionSize: 20  
        #filters: stat,log4j   # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录  
        #useGlobalDataSourceStat: true  # 合并多个DruidDataSource的监控数据  

#-------模板引擎jsp配置-----------
    mvc: 
        view: 
            prefix: /WEB-INF/ #页面默认前缀目录
            suffix: .jsp #响应页面默认后缀
            
#-------指定当前环境的生效配置文件，当然也可以在命令行启动时以入参指定如：java -jar xxx.jar --spring.profiles.active=dev
    profiles: 
        active: dev #表示当前是由哪个环境的配置文件，active的值对应application-xxx.yml 中的xxx

#-------Redis配置-----------
    redis:
        database: 0 #Redis数据库索引（默认为0）
        host: www.seally.cn ##Redis服务器地址
        port: 6379 #Redis服务器连接端口
        password:   #Redis服务器连接密码（默认为空）
        timeout: 30000  #连接超时时间（毫秒）
        pool: 
            max-active: 8 #连接池最大连接数（使用负值表示没有限制）
            max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 8 #连接池中的最大空闲连接
            min-idle: 0 #连接池中的最小空闲连接

#-------mybatis集成配置-----------
mybatis: 
    mapperLocations: classpath:mapper/*.xml             #mapper.xml文件路径
    typeAliasesPackage: com.data.trans.model            #mybatis数据模型实体包路径
    #config: classpath:mybatis-config.xml               #mybatis配置文件的路径 
    
    
#-------Elastic自定义的配置信息-----------
elasticsearch: 
    host: www.seally.cn                              #es服务器ip
    port: 9300                                       #es服务监听端口
    clusterName: es_cluster                                  #es服务集群名称
    poolInitialSize: 10
    poolMaxSize: 20 
    poolMinSize: 8
    poolMaxWait: 6000
    client:     
        import: 
            index: wyglsystemlog                        #es服务器导入目标索引库
            type: pblog                                 #es服务器导入目标索引库类型
            bulkSize: 2000                              #每批提交到es导入的文档数